jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Evaluate release type
      run: ci/evaluate-release.sh
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '8'
        server-id: ${{ env.maven_server_id }}
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Get dependencies
      run: make deps
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      if: ${{ env.ga_release == 'true' }}
      name: Release AMQP Java Client (GA)
      run: 'git config user.name "rabbitmq-ci"

        git config user.email "rabbitmq-ci@users.noreply.github.com"

        ci/release-java-client.sh

        '
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.PACKAGECLOUD_TOKEN }}
        MAVEN_USERNAME: ''
      if: ${{ env.ga_release != 'true' }}
      name: Release AMQP Java Client (Milestone/RC)
      run: 'git config user.name "rabbitmq-ci"

        git config user.email "rabbitmq-ci@users.noreply.github.com"

        ci/release-java-client.sh

        '
name: Release AMQP Java Client
on:
  repository_dispatch:
    types: trigger-ga___release.yml
