jobs:
  build:
    name: Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Checkout tls-gen
      uses: actions/checkout@v4
      with:
        path: ./tls-gen
        repository: rabbitmq/tls-gen
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: Start broker
      run: ci/start-broker.sh
    - continue-on-error: true
      name: Get dependencies
      run: make deps
    - continue-on-error: true
      name: Show version
      run: ./mvnw --version
    - continue-on-error: true
      name: Test with NIO
      run: "./mvnw verify -P '!setup-test-cluster,use-nio' -Drabbitmqctl.bin=DOCKER:rabbitmq\
        \ \\\n  -Dtest-broker.A.nodename=rabbit@$(hostname) -Dmaven.javadoc.skip=true\
        \ \\\n  -Dtest-client-cert.password= -Dtest-tls-certs.dir=rabbitmq-configuration/tls\
        \ \\\n  -Dit.test=ClientTestSuite,FunctionalTestSuite,ServerTestSuite,SslTestSuite\
        \ \\\n  --no-transfer-progress \\\n  -Dnet.bytebuddy.experimental=true\n"
    - continue-on-error: true
      name: Test with blocking IO
      run: './mvnw verify -P ''!setup-test-cluster'' -Drabbitmqctl.bin=DOCKER:rabbitmq
        \

        -Dtest-broker.A.nodename=rabbit@$(hostname) -Dmaven.javadoc.skip=true \

        -Dtest-client-cert.password= -Dtest-tls-certs.dir=rabbitmq-configuration/tls
        \

        -Dit.test=ClientTestSuite,FunctionalTestSuite,ServerTestSuite,SslTestSuite
        \

        --no-transfer-progress \

        -Dnet.bytebuddy.experimental=true

        '
    - continue-on-error: true
      name: Stop broker
      run: docker stop rabbitmq && docker rm rabbitmq
    strategy:
      matrix:
        distribution:
        - temurin
        include:
        - distribution: semeru
          version: '17'
        version:
        - '8'
        - '11'
        - '17'
        - '21'
        - '22'
        - 23-ea
name: Test against supported Java versions (main)
on:
  repository_dispatch:
    types: trigger-ga___test-supported-java-versions-main.yml
