jobs:
  build:
    name: Test against ${{ matrix.rabbitmq-image }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Checkout tls-gen
      uses: actions/checkout@v4
      with:
        path: ./tls-gen
        repository: rabbitmq/tls-gen
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      env:
        RABBITMQ_IMAGE: ${{ matrix.rabbitmq-image }}
      name: Start cluster
      run: ci/start-cluster.sh
    - continue-on-error: true
      name: Get dependencies
      run: make deps
    - continue-on-error: true
      name: Test with NIO
      run: "./mvnw verify -P '!setup-test-cluster,use-nio' -Drabbitmqctl.bin=DOCKER:rabbitmq\
        \ \\\n  -Dtest-broker.A.nodename=rabbit@$(hostname) -Dtest-broker.B.nodename=hare@$(hostname)\
        \ \\\n  -Dmaven.javadoc.skip=true \\\n  -Dtest-client-cert.password= -Dtest-tls-certs.dir=rabbitmq-configuration/tls\
        \ \\\n  --no-transfer-progress\n"
    - continue-on-error: true
      name: Test with blocking IO
      run: './mvnw verify -P ''!setup-test-cluster'' -Drabbitmqctl.bin=DOCKER:rabbitmq
        \

        -Dtest-broker.A.nodename=rabbit@$(hostname) -Dtest-broker.B.nodename=hare@$(hostname)
        \

        -Dmaven.javadoc.skip=true \

        -Dtest-client-cert.password= -Dtest-tls-certs.dir=rabbitmq-configuration/tls
        \

        --no-transfer-progress

        '
    - continue-on-error: true
      name: Stop broker A
      run: docker stop rabbitmq && docker rm rabbitmq
    - continue-on-error: true
      name: Stop broker B
      run: docker stop hare && docker rm hare
    strategy:
      matrix:
        rabbitmq-image:
        - pivotalrabbitmq/rabbitmq:v3.13.x
        - pivotalrabbitmq/rabbitmq:main
name: Test against RabbitMQ alphas
on:
  repository_dispatch:
    types: trigger-ga___test-rabbitmq-alphas.yml
