jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Checkout tls-gen
      uses: actions/checkout@v4
      with:
        path: ./tls-gen
        repository: rabbitmq/tls-gen
    - continue-on-error: true
      name: Checkout GraalVM test project
      uses: actions/checkout@v4
      with:
        path: ./rabbitmq-graal-vm-test
        repository: rabbitmq/rabbitmq-graal-vm-test
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        cache: maven
        java-version: '21'
        version: latest
    - continue-on-error: true
      name: Start broker
      run: ci/start-broker.sh
    - continue-on-error: true
      name: Get dependencies
      run: make deps
    - continue-on-error: true
      name: Install client JAR file
      run: './mvnw clean install -Psnapshots -DskipITs -DskipTests -Dgpg.skip=true
        --no-transfer-progress

        export ARTEFACT_VERSION=$(cat pom.xml | grep -oPm1 "(?<=<version>)[^<]+")

        echo "artefact_version=$ARTEFACT_VERSION" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Package test application
      run: './mvnw --version

        echo "Using RabbitMQ Java Client ${{ env.artefact_version }}"

        ./mvnw -q clean package -Damqp-client.version=${{ env.artefact_version }}
        --no-transfer-progress

        '
      working-directory: rabbitmq-graal-vm-test
    - continue-on-error: true
      name: Start one-time RPC server
      run: ./mvnw -q compile exec:java -Damqp-client.version=${{ env.artefact_version
        }} --no-transfer-progress &
      working-directory: rabbitmq-graal-vm-test
    - continue-on-error: true
      name: Create native image
      run: "native-image -jar target/rabbitmq-graal-vm-test-full.jar \\\n  --initialize-at-build-time=com.rabbitmq.client\
        \ \\\n  --initialize-at-build-time=org.slf4j --no-fallback\n"
      working-directory: rabbitmq-graal-vm-test
    - continue-on-error: true
      name: Use native image program
      run: ./rabbitmq-graal-vm-test-full
      working-directory: rabbitmq-graal-vm-test
    - continue-on-error: true
      name: Stop broker
      run: docker stop rabbitmq && docker rm rabbitmq
name: Test GraalVM native image
on:
  repository_dispatch:
    types: trigger-ga___test-native-image.yml
